name: Keep Web App Alive

on:
  schedule:
    - cron: "*/10 * * * *"  # Every 10 minutes
  workflow_dispatch:

jobs:
  ping-server:
    runs-on: ubuntu-latest
    steps:
      - name: Curl your web app
        run: curl -s -o /dev/null -w "%{http_code}" https://pneumonia-detector-app.onrender.com/
